### ISSUE TITLE
Mic shared on the screenshare stream audio

### ISSUE THREAD

**Issue by JWebCoder** [Vencord/venmic#10]
When sharing the screen and selecting a specific audio source, the mic is also being share on the stream.

Vesktop Flatpack Version 0.4.4
Nobara OS 38

**Comment by Curve** [comment]
Please dump the contents of the log or stdout here (see https://github.com/Vencord/venmic#-debugging).

**Comment by Absolute-Potato** [comment]
I'm not sure I'm setting the env variable correctly because it doesnt seem to create the log file, but heres what it outputs when I run it and begin a stream

```
flatpak run --env=VENMIC_ENABLE_LOG=1 dev.vencord.Vesktop 
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:1216/174700.030667:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1216/174700.423409:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1216/174700.423478:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2023-12-16 17:47:11.569] [venmic] [info] found speakers: 55
[2023-12-16 17:47:14.194] [venmic] [info] created link 91 (-> 80:FR)
[2023-12-16 17:47:14.195] [venmic] [info] created link 87 (-> 80:FL)
[OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidationExt(), eSpsPpsIdStrategy setting (2) with iUsageType (1) not supported! eSpsPpsIdStrategy adjusted to CONSTANT_ID
[OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(3) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(6) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(9) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(12) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(15) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(18) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(21) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(24) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(27) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(30) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(33) is large
[OpenH264] this = 0x0x1c080ae9f150, Warning:Actual input framerate 0.000000 is different from framerate in setting 26.000000, suggest to use other rate control modes
[2023-12-16 17:47:19.741] [venmic] [info] created link 77 (-> 80:FR)
[2023-12-16 17:47:19.742] [venmic] [info] created link 99 (-> 80:FR)
[2023-12-16 17:47:19.743] [venmic] [info] created link 77 (-> 80:FR)
[2023-12-16 17:47:19.743] [venmic] [info] created link 99 (-> 80:FL)

```

**Comment by Curve** [comment]
> I'm not sure I'm setting the env variable correctly because it doesnt seem to create the log file, but heres what it outputs when I run it and begin a stream
> 
> ```
> flatpak run --env=VENMIC_ENABLE_LOG=1 dev.vencord.Vesktop 
> Passing the following arguments to Electron: --ozone-platform-hint=auto
> [3:1216/174700.030667:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [3:1216/174700.423409:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [3:1216/174700.423478:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [2023-12-16 17:47:11.569] [venmic] [info] found speakers: 55
> [2023-12-16 17:47:14.194] [venmic] [info] created link 91 (-> 80:FR)
> [2023-12-16 17:47:14.195] [venmic] [info] created link 87 (-> 80:FL)
> [OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidationExt(), eSpsPpsIdStrategy setting (2) with iUsageType (1) not supported! eSpsPpsIdStrategy adjusted to CONSTANT_ID
> [OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
> [OpenH264] this = 0x0x1c080ae9f150, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(3) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(6) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(9) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(12) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(15) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(18) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(21) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(24) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(27) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(30) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:[Rc] iDid = 0,iContinualSkipFrames(33) is large
> [OpenH264] this = 0x0x1c080ae9f150, Warning:Actual input framerate 0.000000 is different from framerate in setting 26.000000, suggest to use other rate control modes
> [2023-12-16 17:47:19.741] [venmic] [info] created link 77 (-> 80:FR)
> [2023-12-16 17:47:19.742] [venmic] [info] created link 99 (-> 80:FR)
> [2023-12-16 17:47:19.743] [venmic] [info] created link 77 (-> 80:FR)
> [2023-12-16 17:47:19.743] [venmic] [info] created link 99 (-> 80:FL)
> 
> ```

When run in Flatpak the log file will also be created inside the Flatpak container, please look there and upload it as well, also a qpwgraph (or similar) screenshot would also help ^^

**Comment by Curve** [comment]
I've added a new default-on setting `ignore_devices` which will prevent microphones or speakers from being linked to the virtual-mic.

I am still not sure how this would happen in the first place though - anyhow it's good to have a fail-safe for this now.
