### ISSUE TITLE
Go Live Screenshare audio is mono

### ISSUE THREAD

**Issue by Kyuunex** [Vencord/venmic#11]
details
Arch Linux
hyprland 0.33.1-2
pipewire 1:1.0.0-2
xdg-desktop-portal-hyprland 1.2.5-1

**Comment by Curve** [comment]
Please dump the contents of the log or stdout here (see https://github.com/Vencord/venmic#-debugging).

**Comment by Curve** [comment]
Closed in favor of #12

**Comment by Kyuunex** [comment]
Oh, i didn't noticed you moved this nevermind
