### ISSUE TITLE
[Bug] Vesktop crashes upon attempting to screenshare

### ISSUE THREAD

**Issue by FirewallDaProtogen** [Vencord/venmic#26]
### Discord Account

firewalldaprotogen

### Operating System

Linux Mint 21.3 Cinnamon

### Linux Only ~ Desktop Environment

Cinnamon 6.0.4

### Package Type

Flatpak

### What happens when the bug or crash occurs?

once i click "share your screen" the screen select appears as normal. however, once i select a screen or window to share, the program hangs and i have to force quit it in order for it to continue working

### What is the expected behaviour?

i expect that once i select a screen/window to share, i can change options then share it

### How do you recreate this bug or crash?

1. get in a voice chat
2. try to share screen

### Debug Logs

(note: bash prompt shows "C:\home\nova" because of "Chicago95")
```
C:\home\nova> flatpak  run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop
Passing the following arguments to Electron: --enable-speech-dispatcher
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Gtk-Message: 21:29:02.724: Failed to load module "xapp-gtk3-module"
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[2024-07-12 21:29:39.093] [venmic] [warning] [patchbay] (get) pipewire was not detected as main audio server
[2024-07-12 21:29:40.093] [venmic] [error] [patchbay] (init) pw_receiver failed to respond within 1 second, aborting
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Curve** [comment]
You need to install pipewire to share with sound.

The initial lag (1 or 5 seconds) is normal as that's the timeout for connecting to pipewire, however, after the initial lag you should be able to continue using vesktop

**Comment by FirewallDaProtogen** [comment]
pipewire is already installed
`C:\home\nova> sudo apt install pipewire
[sudo] password for nova:           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pipewire is already the newest version (0.3.48-1ubuntu3).
The following packages were automatically installed and are no longer required:
  pass qrencode uidmap xclip
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
`

**Comment by Vendicated** [comment]
https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e#install

**Comment by Curve** [comment]
Try to install wireplumber , afaik mint ships with media session and the mint build of that is really buggy, which is also why vesktop locks up

**Comment by FirewallDaProtogen** [comment]
i have installed pipewire, but the crash persists, now with nothing in the terminal log

**Comment by Curve** [comment]
> i have installed pipewire, but the crash persists, now with nothing in the terminal log
> 
> edit: tired it again, now the log says the following: `[2024-07-14 09:30:19.046] [venmic] [error] [patchbay] (has_pipewire) failed to connect pulse context [2024-07-14 09:30:19.046] [venmic] [error] [patchbay] (has_pipewire) result timed out [2024-07-14 09:30:49.070] [venmic] [error] [patchbay] (has_pipewire) failed to connect pulse context [2024-07-14 09:30:49.070] [venmic] [error] [patchbay] (has_pipewire) result timed out [2024-07-14 09:30:49.070] [venmic] [warning] [patchbay] (get) pipewire was not detected as main audio server [2024-07-14 09:30:50.070] [venmic] [error] [patchbay] (init) pw_receiver failed to respond within 1 second, aborting `

The log hints at your audio setup being completely broken. Neither pulse nor pipewire is reachable.
Make sure you have the audio system properly configured. I'll try to reproduce this on mint as soon as I can - From the last I conducted I came to the conclusion that the default pipewire setup on mint is borked, they don't use it as their main audio server, but send mixed signals to venmic causing it to lock-up, this notably does not happen when wireplumber is installed (or on any other distro)

**Comment by FirewallDaProtogen** [comment]
ill probably try building pipewire from source tomorrow, because the version on my system (and when i use apt) is really old

**Comment by FirewallDaProtogen** [comment]
i installed a bunch of pipewire things from synaptic and it works now
