### ISSUE TITLE
Release built module in GitHub Releases

### ISSUE THREAD

**Issue by NotNite** [Vencord/venmic#32]
Hi! We're using venmic over in [rocketship](https://github.com/moonlight-mod/rocketship) but right now there's just a venmic.node sitting in the repository. We download venmic into the Discord install so a moonlight extension can `require` it.

It would be nice if this repository had releases with the module attached as an artifact, so we don't have to keep a copy of venmic in our repository. Thanks!

**Comment by Vendicated** [comment]
you're supposed to use https://www.npmjs.com/package/@vencord/venmic, it contains binaries in the prebuild folder

https://github.com/Vencord/Vesktop/blob/ccff1ac3efde2b4fc826d2f411d79e42d80dcb70/package.json#L30-L32

**Comment by Curve** [comment]
> you're supposed to use https://www.npmjs.com/package/@vencord/venmic
> 
> https://github.com/Vencord/Vesktop/blob/ccff1ac3efde2b4fc826d2f411d79e42d80dcb70/package.json#L30-L32

This, is there any reason you require "normal" build artifacts?

**Comment by NotNite** [comment]
I'm aware, but the extension that uses venmic is supposed to function with venmic being optional. Also, having venmic as a dependency requires CMake to be installed, which makes contributing on not-Linux much more annoying (and breaks our extension CI). rocketship isn't a custom Discord client as much as a custom Electron build that downloads venmic with it. Is it possible to directly download the binary from npm, perhaps?

**Comment by Vendicated** [comment]
> having venmic as a dependency requires CMake to be installed

i don't think this is true? the npm module contains prebuilds for x64 and arm64, only if you're on a different platform it has to build. this is how vesktop does it too, it just copies the prebuilds into our asar

in any case you should just be able to download the package from https://registry.npmjs.org/@vencord/venmic/-/venmic-6.1.0.tgz and it will contain the binaries in the prebuilds folder

**Comment by NotNite** [comment]
> i don't think this is true? the npm module contains prebuilds for x64 and arm64, only if you're on a different platform it has to build. this is how vesktop does it too, it just copies the prebuilds into our asar

moonlight targets more than Linux (macOS and Windows). In that case, running `pnpm i` will cause it to try and install and build venmic. This is why dynamically loading it is desired.

> in any case you should just be able to download the package from https://registry.npmjs.org/@vencord/venmic/-/venmic-6.1.0.tgz and it will contain the binaries in the prebuilds folder

I'll go with that, thanks!

**Comment by Vendicated** [comment]
> moonlight targets more than Linux (macOS and Windows). In that case, running pnpm i will cause it to try and install and build venmic. This is why dynamically loading it is desired.

the package is marked as linux only. if you mark it as [`optionalDependency`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies), it will just print a warning and skip installing it on other platforms (hard dependency will instead cause an error)
