### ISSUE TITLE
Excessively large buffers cause excessive latency (chat lag)

### ISSUE THREAD

**Issue by pallaswept** [Vencord/venmic#35]
### ✍️ Bug Description

By default, vesktop has very large audio buffers. This results in high latency of audio in and out of the app, meaning that even with a good network connection, you have lots of 'chat lag', where you end up talking over people/people talk over you, because you're hearing everything they say, late, and they hear everything you say, late.

### 🔁 Steps to reproduce

Audio chat in discord

### 🗒️ Debug Output

Streaming rn so I can't grab the logs for you. 

### ❔ Expected behavior

Use the smallest possible buffer size, to minimize lag.

This can be tested with the command line option `--audio-buffer-size=256` (replace 256 with the appropriate buffer size for your system) 

### 📦 Vesktop Version

1.5.3

### 🖥️ Distribution

Tumbleweed

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided

**Comment by Curve** [comment]
This is not venmic related.

**Comment by pallaswept** [comment]
> This is not venmic related.

OK where should I file it? I just now logged another issue about venmic on the vesktop github and it was closed and I was told to come here instead.

**Comment by Curve** [comment]
> > This is not venmic related.
> 
> OK where should I file it? I just now logged another issue about venmic on the vesktop github and it was closed and I was told to come here instead.

The issue description makes it clear that this is related to electron / vesktop.

Venmic is only used for screenshare audio sharing.

**Comment by pallaswept** [comment]
> Venmic is only used for screenshare audio sharing.

Thanks! The name was a little misleading :D
