### ISSUE TITLE
Both methods not working

### ISSUE THREAD

**Issue by Chaotic-Oven** [Vencord/venmic#8]
The first one said it couldn't find pulseaudio even though it is installed (also had a Pipewire thing going on but I fixed that)

Second one needed "pnpm'" even though it's not in my distro's repos (I use Linux Mint)

**Comment by Curve** [comment]
To compile this you need the development packages.

pnpm can be installed by following the official installation instructions: https://pnpm.io/installation.

If you simply want to use venmic, please install Vekstop as it comes bundled with venmic.
