### ISSUE TITLE
[Linux Mint] Screen Share on Vesktop captures microphone instead of application audio

### ISSUE THREAD

**Issue by dylanh12210** [Vencord/venmic#9]
Viewers are unable to hear the streamed app and hear an echo of me.
![image](https://github.com/Vencord/venmic/assets/32474156/87951ec8-5576-464d-8bfc-e4e25f8d9a07)
Chromium input (red) appears and disappears as I start and stop streaming, but vencord-screen-share appears when I stream, but persists after I stop streaming.

Linux Mint 21.2 w/ PipeWire 1.0.0
Vesktop v0.4.4 (flatpak)

**Comment by Curve** [comment]
Please set the `VENMIC_ENABLE_LOG` environment variable and share the log that should reside in the `XDG_STATE_HOME`.

Not sure whether or not the log is created inside of the Flatpak container or not

**Comment by dylanh12210** [comment]
No logs appear in ~/.local/state/

**Comment by dylanh12210** [comment]
unsure if this is a venmic issue

**Comment by Curve** [comment]
> No logs appear in ~/.local/state/

Probably because running in Flatpak, please refer to the discord, Ven provided you with instructions for it

**Comment by Curve** [comment]
From what I can see this is not a Venmic but rather a Vesktop issue
